layout_spectrum: 0.2228512044394813
typography_spectrum: 0.042530684295838866
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.1973593045206796
  lightness: 0.5066769240230395
  saturation: 0.8776179939119311
  rhythmicContrast: 0.6902193777559159
name: SafetyLee
cta: {}
analytics: {}
opengraph:
  type: ''
  appId: ''
purpose:
  - type: external
    label: Free Access during Beta
    url: 'https://techspeare.typeform.com/to/AB1yHl'
  - type: external
    label: Experts/Advocates earn up to $50k
    url: 'https://techspeare.typeform.com/to/o2UBvq'
title: Escape Medical Error in Healthcare
description: >-
  3 million die and 30 million suffer serious injury every year. We help you ask
  the right question and take the right action to keep loved ones safe.
author:
  name: Ramm
  url: 'https://safetylee.com'
  email: ramm@techspeare.com
content_rating:
  adult: false
navigation:
  - name: Investor
    id: cbce7db0-08db-4010-be3d-b7e045f67c01
    type: content
  - name: Blog
    url: 'https://thegrid.ai/techspeare'
    type: external
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/1067b79f-490b-45c3-9f5e-67cfbac03892.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/1067b79f-490b-45c3-9f5e-67cfbac03892.jpg
    metadata:
      '@type': MediaObject
      '@context': 'http://schema.org'
      keywords: []
      publisher:
        name: The-grid-user-content
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
      author: []
      starred: false
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/8dc43777-ba6d-4cc7-a0d7-62eba9b48b7c.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/8dc43777-ba6d-4cc7-a0d7-62eba9b48b7c.jpg
    metadata:
      '@type': MediaObject
      '@context': 'http://schema.org'
      keywords: []
      publisher:
        name: The-grid-user-content
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
      author: []
      starred: false
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
