typography_spectrum: 0.5595605102395362
content_rating:
  adult: false
color:
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
  brandStrength: 0.03459041684119049
  lightness: 0.1220322674737856
  saturation: 0.6197445338494191
  rhythmicContrast: 0.14537892216171075
github: true
opengraph:
  type: ''
  appId: ''
layout_spectrum: 0.32771140462792675
analytics:
  google: UA-99034321-1
author:
  name: Ramm
  url: 'https://safetylee.com'
  email: ramm@techspeare.com
name: SafetyLee
cta: {}
navigation:
  - name: buyers beware blog
    id: fd38c272-9e50-4f41-a6c5-1721baddecc4
    type: content
  - name: Privacy Policy
    id: 7d6375f3-e8fe-4494-bd83-d71f1c3e93c7
    type: content
  - name: Terms of Use
    id: 03cb4e72-c4a6-47bb-bc3b-334cc5d11779
    type: content
title: Escape Harm in Healthcare
content: []
description: >-
  Preventable harm in healthcare is neither tracked nor disclosed. The right
  questions and actions can keep you and your family safe.
purpose:
  - type: external
    label: Bot for Advocates
    url: >-
      https://thegrid.ai/safetylee/how-safe-are-you-in-healthcare-even-if-you-are-a-doctor
  - type: external
    url: 'https://sowl.co/G5wkv'
    label: Get SafetyLee Now
