name: safety lee
favicon: null
layout_spectrum: 0.6805095872841775
typography_spectrum: 0.42949655489064753
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8763368234504014
  lightness: 0.3032477302476764
  saturation: 0.6207067158538848
  rhythmicContrast: 0.25073066749610007
purpose: []
