name: SafetyLee
layout_spectrum: 0.451628534845307
typography_spectrum: 0.5822721135191213
cta: {}
analytics: {}
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
  brandStrength: 0.6322971708705594
  lightness: 0.3028758109178357
  saturation: 0.9185166582335156
  rhythmicContrast: 0.07044830078904582
purpose:
  - type: external
    label: Free Access during Beta
    url: 'https://techspeare.typeform.com/to/AB1yHl'
  - type: external
    label: Experts/Advocates earn up to $50k
    url: 'https://techspeare.typeform.com/to/o2UBvq'
title: Escape Medical Error in Healthcare (under construction)
description: 'Like Waze for Maps, use SafetyLee to navigate healthcare safely'
author:
  name: Ramm
  url: 'https://safetylee.com'
  email: ramm@techspeare.com
content_rating:
  adult: false
navigation:
  - name: Investor
    id: cbce7db0-08db-4010-be3d-b7e045f67c01
    type: content
  - name: Blog
    url: 'https://thegrid.ai/techspeare'
    type: external
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/1067b79f-490b-45c3-9f5e-67cfbac03892.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/1067b79f-490b-45c3-9f5e-67cfbac03892.jpg
    metadata:
      '@type': MediaObject
      '@context': 'http://schema.org'
      keywords: []
      publisher:
        name: The-grid-user-content
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
      author: []
      starred: false
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/8dc43777-ba6d-4cc7-a0d7-62eba9b48b7c.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/8dc43777-ba6d-4cc7-a0d7-62eba9b48b7c.jpg
    metadata:
      '@type': MediaObject
      '@context': 'http://schema.org'
      keywords: []
      publisher:
        name: The-grid-user-content
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
      author: []
      starred: false
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
