layout_spectrum: 0.32771140462792675
typography_spectrum: 0.5595605102395362
color:
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
  brandStrength: 0.03459041684119049
  lightness: 0.1220322674737856
  saturation: 0.6197445338494191
  rhythmicContrast: 0.14537892216171075
name: SafetyLee
cta: {}
analytics:
  google: UA-99034321-1
opengraph:
  type: ''
  appId: ''
purpose:
  - type: external
    label: My Patient-Safety Acumen Score
    url: >-
      https://thegrid.ai/safetylee/how-safe-are-you-in-healthcare-even-if-you-are-a-doctor
  - type: external
    url: 'https://sowl.co/G5wkv'
    label: Get SafetyLee Now
title: Escape Medical Error in Healthcare
description: >-
  Preventable harm in healthcare is neither tracked nor disclosed. Get
  superpowers (right questions and actions) to keep you and your loved ones
  safe.
author:
  name: Ramm
  url: 'https://safetylee.com'
  email: ramm@techspeare.com
content_rating:
  adult: false
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FNrbdQFnHBGI%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DNrbdQFnHBGI&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FNrbdQFnHBGI%2Fhqdefault.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: Rammohan C B
          url: 'https://www.youtube.com/channel/UCuJvbo6YALQNV1ho7rJZ5Ww'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vflz7uhzw.ico'
        domain: youtu.be
      keywords:
        - ''
      description: Uploaded by Rammohan C B on 2017-05-12.
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=NrbdQFnHBGI&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=NrbdQFnHBGI&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=NrbdQFnHBGI&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=NrbdQFnHBGI&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=NrbdQFnHBGI&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=NrbdQFnHBGI'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=NrbdQFnHBGI
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=NrbdQFnHBGI
          package: '544007664'
          namespace: google
          type: ios
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://youtu.be/NrbdQFnHBGI'
      title: '583335999'
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
