typography_spectrum: 0.5595605102395362
content_rating:
  adult: false
color:
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
  brandStrength: 0.03459041684119049
  lightness: 0.1220322674737856
  saturation: 0.6197445338494191
  rhythmicContrast: 0.14537892216171075
github: true
opengraph:
  type: ''
  appId: ''
layout_spectrum: 0.32771140462792675
analytics:
  google: UA-99034321-1
author:
  name: Ramm
  url: 'https://safetylee.com'
  email: ramm@techspeare.com
name: SafetyLee
cta: {}
navigation:
  - name: buyers beware blog
    id: fd38c272-9e50-4f41-a6c5-1721baddecc4
    type: content
  - name: Privacy Policy
    id: 7d6375f3-e8fe-4494-bd83-d71f1c3e93c7
    type: content
  - name: Terms of Use
    id: 03cb4e72-c4a6-47bb-bc3b-334cc5d11779
    type: content
title: Escape Harm in Healthcare
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://s3-us-west-2.amazonaws.com/the-grid-img/p/01df82431d4a32a3539813e5309a9035ed9707ba.jpg">
    src: >-
      https://s3-us-west-2.amazonaws.com/the-grid-img/p/01df82431d4a32a3539813e5309a9035ed9707ba.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://s3-us-west-2.amazonaws.com'
        name: .s3-us-west-2.amazonaws.com
        favicon: null
        domain: imgflo.herokuapp.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      isBasedOnUrl: >-
        https://imgflo.herokuapp.com/graph/2b2431f8e7ba7b0/552827c3f1eef1daeb2bcb2cf53a361f/croprotate.jpg?cropheight=274&cropwidth=480&degrees=0&input=https%3A%2F%2Fimg.youtube.com%2Fvi%2FJ5Wx4245RQw%2Fhqdefault.jpg&x=0&y=46
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: >-
  Preventable harm in healthcare is neither tracked nor disclosed. The right
  questions and actions can keep you and your family safe.
purpose:
  - type: external
    label: Bot for Advocates
    url: >-
      https://thegrid.ai/safetylee/how-safe-are-you-in-healthcare-even-if-you-are-a-doctor
  - type: external
    url: 'https://sowl.co/G5wkv'
    label: Get SafetyLee Now
